#![no_std]

use soroban_sdk::{
    contract, contractimpl, contracttype, contracterror,
    crypto::bn254::{Bn254G1Affine, Bn254G2Affine, Fr},
    Address, BytesN, Env, U256, Vec,
};

/// Contract 5: Groth16 ZK-SNARK Verifier
///
/// Verifies Groth16 zero-knowledge proofs on-chain using BN254.
///
/// Groth16 is the most widely used zk-SNARK system, used by:
/// - Tornado Cash (privacy mixer)
/// - Zcash (shielded transactions)
/// - zkSync, Polygon zkEVM (rollups)
/// - Many Circom-based applications
///
/// Verification equation:
/// e(A, B) = e(alpha, beta) * e(L, gamma) * e(C, delta)
///
/// Where L = sum(public_inputs[i] * IC[i])
///
/// Rearranged for pairing check (product = 1):
/// e(-A, B) * e(alpha, beta) * e(L, gamma) * e(C, delta) = 1
#[contract]
pub struct Groth16VerifierContract;

/// Groth16 Verification Key
///
/// Generated by the trusted setup, contains the public parameters
/// needed to verify proofs for a specific circuit.
#[contracttype]
#[derive(Clone)]
pub struct VerificationKey {
    /// alpha * G1
    pub alpha_g1: Bn254G1Affine,
    /// beta * G2
    pub beta_g2: Bn254G2Affine,
    /// gamma * G2
    pub gamma_g2: Bn254G2Affine,
    /// delta * G2
    pub delta_g2: Bn254G2Affine,
    /// IC (input commitments): IC[0] + sum(public_inputs[i] * IC[i+1])
    /// First element is the constant term, rest correspond to public inputs
    pub ic: Vec<Bn254G1Affine>,
}

/// Groth16 Proof
///
/// Generated by the prover, contains the evidence that the prover
/// knows a valid witness satisfying the circuit constraints.
#[contracttype]
#[derive(Clone)]
pub struct Proof {
    /// Point A (G1)
    pub a: Bn254G1Affine,
    /// Point B (G2)
    pub b: Bn254G2Affine,
    /// Point C (G1)
    pub c: Bn254G1Affine,
}

/// Contract errors
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum VerifierError {
    /// Contract not initialized (no admin set)
    NotInitialized = 1,
    /// Caller is not the admin
    Unauthorized = 2,
    /// Contract already initialized
    AlreadyInitialized = 3,
}

/// Storage keys
#[contracttype]
pub enum DataKey {
    /// The admin address (can set VK and upgrade)
    Admin,
    /// The verification key
    VerificationKey,
}

#[contractimpl]
impl Groth16VerifierContract {
    /// Initialize the contract with an admin address.
    ///
    /// Must be called once after deployment. The admin can set the VK and upgrade.
    pub fn initialize(env: Env, admin: Address) -> Result<(), VerifierError> {
        if env.storage().persistent().has(&DataKey::Admin) {
            return Err(VerifierError::AlreadyInitialized);
        }
        admin.require_auth();
        env.storage().persistent().set(&DataKey::Admin, &admin);
        Ok(())
    }

    /// Store a verification key (admin only).
    ///
    /// This should be called once after deployment with the VK
    /// generated from the trusted setup.
    pub fn set_verification_key(env: Env, admin: Address, vk: VerificationKey) -> Result<(), VerifierError> {
        Self::require_admin(&env, &admin)?;
        env.storage()
            .persistent()
            .set(&DataKey::VerificationKey, &vk);
        Ok(())
    }

    /// Get the stored verification key.
    pub fn get_verification_key(env: Env) -> Option<VerificationKey> {
        env.storage().persistent().get(&DataKey::VerificationKey)
    }

    /// Upgrade this contract to a new WASM (admin only).
    pub fn upgrade(env: Env, admin: Address, new_wasm_hash: BytesN<32>) -> Result<(), VerifierError> {
        Self::require_admin(&env, &admin)?;
        env.deployer().update_current_contract_wasm(new_wasm_hash);
        Ok(())
    }

    /// Get the admin address.
    pub fn get_admin(env: Env) -> Result<Address, VerifierError> {
        env.storage()
            .persistent()
            .get(&DataKey::Admin)
            .ok_or(VerifierError::NotInitialized)
    }

    /// Verify caller is the admin.
    fn require_admin(env: &Env, admin: &Address) -> Result<(), VerifierError> {
        admin.require_auth();
        let stored_admin: Address = env
            .storage()
            .persistent()
            .get(&DataKey::Admin)
            .ok_or(VerifierError::NotInitialized)?;
        if *admin != stored_admin {
            return Err(VerifierError::Unauthorized);
        }
        Ok(())
    }

    /// Verify a Groth16 proof with the stored verification key.
    ///
    /// # Arguments
    /// * `proof` - The Groth16 proof (A, B, C points)
    /// * `public_inputs` - Public inputs to the circuit
    ///
    /// # Returns
    /// true if the proof is valid
    pub fn verify(env: Env, proof: Proof, public_inputs: Vec<U256>) -> bool {
        let vk: VerificationKey = env
            .storage()
            .persistent()
            .get(&DataKey::VerificationKey)
            .expect("Verification key not set");

        Self::verify_with_vk(env, vk, proof, public_inputs)
    }

    /// Verify a Groth16 proof with a provided verification key.
    ///
    /// Useful for one-off verifications or testing.
    pub fn verify_with_vk(
        env: Env,
        vk: VerificationKey,
        proof: Proof,
        public_inputs: Vec<U256>,
    ) -> bool {
        // Check IC length matches public inputs + 1
        if vk.ic.len() != public_inputs.len() + 1 {
            return false;
        }

        let bn254 = env.crypto().bn254();

        // Compute L = IC[0] + sum(public_inputs[i] * IC[i+1])
        let mut vk_x = vk.ic.get(0).unwrap();

        for i in 0..public_inputs.len() {
            let input = public_inputs.get(i).unwrap();
            let ic_point = vk.ic.get(i + 1).unwrap();
            let scalar = Fr::from_u256(input);
            let term = bn254.g1_mul(&ic_point, &scalar);
            vk_x = bn254.g1_add(&vk_x, &term);
        }

        // Negate A for the pairing check
        let neg_a = -proof.a;

        // Prepare pairing inputs
        // e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) = 1
        let mut g1_points = Vec::new(&env);
        let mut g2_points = Vec::new(&env);

        // -A, B
        g1_points.push_back(neg_a);
        g2_points.push_back(proof.b);

        // alpha, beta
        g1_points.push_back(vk.alpha_g1);
        g2_points.push_back(vk.beta_g2);

        // vk_x, gamma
        g1_points.push_back(vk_x);
        g2_points.push_back(vk.gamma_g2);

        // C, delta
        g1_points.push_back(proof.c);
        g2_points.push_back(vk.delta_g2);

        // Verify the pairing equation
        bn254.pairing_check(g1_points, g2_points)
    }

    /// Compute the linear combination of IC points with public inputs.
    ///
    /// L = IC[0] + sum(inputs[i] * IC[i+1])
    ///
    /// This is exposed for debugging and testing.
    pub fn compute_vk_x(
        env: Env,
        ic: Vec<Bn254G1Affine>,
        public_inputs: Vec<U256>,
    ) -> Bn254G1Affine {
        let bn254 = env.crypto().bn254();

        let mut result = ic.get(0).unwrap();

        for i in 0..public_inputs.len() {
            let input = public_inputs.get(i).unwrap();
            let ic_point = ic.get(i + 1).unwrap();
            let scalar = Fr::from_u256(input);
            let term = bn254.g1_mul(&ic_point, &scalar);
            result = bn254.g1_add(&result, &term);
        }

        result
    }

    /// Create a simple proof structure (for testing).
    ///
    /// In production, proofs are generated off-chain by the prover.
    pub fn create_proof(
        _env: Env,
        a: Bn254G1Affine,
        b: Bn254G2Affine,
        c: Bn254G1Affine,
    ) -> Proof {
        Proof { a, b, c }
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::{BytesN, Env};
    use soroban_sdk::testutils::Address as _;

    // BN254 G1 generator: (1, 2)
    fn g1_generator(env: &Env) -> Bn254G1Affine {
        let mut bytes = [0u8; 64];
        bytes[31] = 1; // X = 1
        bytes[63] = 2; // Y = 2
        Bn254G1Affine::from_bytes(BytesN::from_array(env, &bytes))
    }

    // G1 identity (point at infinity): (0, 0)
    fn g1_identity(env: &Env) -> Bn254G1Affine {
        Bn254G1Affine::from_bytes(BytesN::from_array(env, &[0u8; 64]))
    }

    // BN254 G2 generator
    // This is a simplified test point - real G2 generator is more complex
    fn g2_generator(env: &Env) -> Bn254G2Affine {
        // G2 generator coordinates (simplified for testing)
        // Real generator:
        // x = (10857046999023057135944570762232829481370756359578518086990519993285655852781,
        //      11559732032986387107991004021392285783925812861821192530917403151452391805634)
        // y = (8495653923123431417604973247489272438418190587263600148770280649306958101930,
        //      4082367875863433681332203403145435568316851327593401208105741076214120093531)

        // For testing, we'll use a point derived from the generator
        // In production, use the actual G2 generator
        let mut bytes = [0u8; 128];
        // This is placeholder - real tests need actual G2 points
        bytes[31] = 1;
        bytes[63] = 0;
        bytes[95] = 1;
        bytes[127] = 0;
        Bn254G2Affine::from_bytes(BytesN::from_array(env, &bytes))
    }

    #[test]
    fn test_store_verification_key() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);
        let admin = Address::generate(&env);

        client.initialize(&admin);

        let g1 = g1_generator(&env);
        let g2 = g2_generator(&env);

        let mut ic = Vec::new(&env);
        ic.push_back(g1.clone());
        ic.push_back(g1.clone());

        let vk = VerificationKey {
            alpha_g1: g1.clone(),
            beta_g2: g2.clone(),
            gamma_g2: g2.clone(),
            delta_g2: g2.clone(),
            ic,
        };

        client.set_verification_key(&admin, &vk);

        let retrieved = client.get_verification_key();
        assert!(retrieved.is_some());
    }

    #[test]
    fn test_compute_vk_x() {
        let env = Env::default();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let g = g1_generator(&env);

        // IC = [G, G, G] (3 points for 2 public inputs)
        let mut ic = Vec::new(&env);
        ic.push_back(g.clone());
        ic.push_back(g.clone());
        ic.push_back(g.clone());

        // public_inputs = [1, 1]
        let mut inputs = Vec::new(&env);
        inputs.push_back(U256::from_u32(&env, 1));
        inputs.push_back(U256::from_u32(&env, 1));

        // vk_x = IC[0] + 1*IC[1] + 1*IC[2] = G + G + G = 3*G
        let vk_x = client.compute_vk_x(&ic, &inputs);

        // Verify by computing 3*G directly
        let three = Fr::from_u256(U256::from_u32(&env, 3));
        let expected = env.crypto().bn254().g1_mul(&g, &three);

        assert_eq!(vk_x, expected);
    }

    #[test]
    fn test_compute_vk_x_zero_inputs() {
        let env = Env::default();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let g = g1_generator(&env);

        // IC = [G, G] (2 points for 1 public input)
        let mut ic = Vec::new(&env);
        ic.push_back(g.clone());
        ic.push_back(g.clone());

        // public_inputs = [0]
        let mut inputs = Vec::new(&env);
        inputs.push_back(U256::from_u32(&env, 0));

        // vk_x = IC[0] + 0*IC[1] = G + 0 = G
        let vk_x = client.compute_vk_x(&ic, &inputs);

        assert_eq!(vk_x, g);
    }

    #[test]
    fn test_proof_structure() {
        let env = Env::default();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let g1 = g1_generator(&env);
        let g2 = g2_generator(&env);

        let proof = client.create_proof(&g1, &g2, &g1);

        assert_eq!(proof.a, g1);
        assert_eq!(proof.c, g1);
    }

    // Note: Full verification tests require valid proofs generated from
    // a real trusted setup. The pairing check will fail with random points.

    // =========================================================================
    // SECURITY TESTS — Attack Scenarios
    // =========================================================================

    /// ATTACK: Double-initialize to hijack admin role
    #[test]
    fn test_security_double_init_blocked() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let real_admin = Address::generate(&env);
        let attacker = Address::generate(&env);

        client.initialize(&real_admin);

        // Attacker tries to re-initialize to become admin
        let result = client.try_initialize(&attacker);
        assert!(result.is_err());

        // Verify original admin is still in place
        assert_eq!(client.get_admin(), real_admin);
    }

    /// ATTACK: Non-admin tries to replace the verification key
    #[test]
    fn test_security_unauthorized_vk_replacement() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let admin = Address::generate(&env);
        let attacker = Address::generate(&env);

        client.initialize(&admin);

        let g1 = g1_generator(&env);
        let g2 = g2_generator(&env);
        let mut ic = Vec::new(&env);
        ic.push_back(g1.clone());
        let malicious_vk = VerificationKey {
            alpha_g1: g1.clone(),
            beta_g2: g2.clone(),
            gamma_g2: g2.clone(),
            delta_g2: g2.clone(),
            ic,
        };

        // Attacker calls set_verification_key — must fail
        let result = client.try_set_verification_key(&attacker, &malicious_vk);
        assert!(result.is_err());
    }

    /// ATTACK: set_verification_key before initialize (bypass admin check)
    #[test]
    fn test_security_set_vk_before_init() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let attacker = Address::generate(&env);
        let g1 = g1_generator(&env);
        let g2 = g2_generator(&env);
        let mut ic = Vec::new(&env);
        ic.push_back(g1.clone());
        let vk = VerificationKey {
            alpha_g1: g1,
            beta_g2: g2.clone(),
            gamma_g2: g2.clone(),
            delta_g2: g2,
            ic,
        };

        // No initialize() called — should fail with NotInitialized
        let result = client.try_set_verification_key(&attacker, &vk);
        assert!(result.is_err());
    }

    /// ATTACK: Non-admin tries to upgrade contract code
    #[test]
    fn test_security_unauthorized_upgrade() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let admin = Address::generate(&env);
        let attacker = Address::generate(&env);

        client.initialize(&admin);

        let fake_hash = BytesN::from_array(&env, &[0xABu8; 32]);
        let result = client.try_upgrade(&attacker, &fake_hash);
        assert!(result.is_err());
    }

    /// ATTACK: Upgrade before initialize
    #[test]
    fn test_security_upgrade_before_init() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let attacker = Address::generate(&env);
        let fake_hash = BytesN::from_array(&env, &[0xABu8; 32]);

        // No initialize — should fail
        let result = client.try_upgrade(&attacker, &fake_hash);
        assert!(result.is_err());
    }

    /// INVARIANT: verify() fails gracefully when no VK is stored
    #[test]
    #[should_panic(expected = "Verification key not set")]
    fn test_security_verify_without_vk() {
        let env = Env::default();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let g1 = g1_generator(&env);
        let g2 = g2_generator(&env);
        let proof = Proof { a: g1.clone(), b: g2, c: g1 };
        let inputs = Vec::new(&env);

        // Should panic — no VK stored
        client.verify(&proof, &inputs);
    }

    /// INVARIANT: verify() rejects mismatched public input count
    #[test]
    fn test_security_verify_wrong_input_count() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register(Groth16VerifierContract, ());
        let client = Groth16VerifierContractClient::new(&env, &contract_id);

        let admin = Address::generate(&env);
        client.initialize(&admin);

        let g1 = g1_generator(&env);
        let g2 = g2_generator(&env);

        // VK with IC length 2 (expects 1 public input)
        let mut ic = Vec::new(&env);
        ic.push_back(g1.clone());
        ic.push_back(g1.clone());
        let vk = VerificationKey {
            alpha_g1: g1.clone(),
            beta_g2: g2.clone(),
            gamma_g2: g2.clone(),
            delta_g2: g2.clone(),
            ic,
        };
        client.set_verification_key(&admin, &vk);

        let proof = Proof { a: g1.clone(), b: g2, c: g1 };

        // Pass 0 inputs when VK expects 1 — should return false
        let empty_inputs = Vec::new(&env);
        assert!(!client.verify(&proof, &empty_inputs));

        // Pass 3 inputs when VK expects 1 — should return false
        let mut too_many = Vec::new(&env);
        too_many.push_back(U256::from_u32(&env, 1));
        too_many.push_back(U256::from_u32(&env, 2));
        too_many.push_back(U256::from_u32(&env, 3));
        assert!(!client.verify(&proof, &too_many));
    }
}
