/**
 * Identity Attestation Proof Verifier
 *
 * This script verifies a proof generated by generate-proof.js
 * The same verification logic will run on-chain via groth16-verifier
 */

const snarkjs = require('snarkjs');
const fs = require('fs');
const path = require('path');

async function main() {
  console.log('');
  console.log('==========================================');
  console.log(' Identity Attestation Proof Verifier');
  console.log('==========================================');
  console.log('');

  // ============================================
  // STEP 1: Load proof and public signals
  // ============================================
  console.log('Step 1: Loading proof data...');

  const proofPath = path.join(__dirname, '..', 'build', 'proof.json');
  const publicPath = path.join(__dirname, '..', 'build', 'public.json');
  const vkeyPath = path.join(__dirname, '..', 'keys', 'verification_key.json');

  if (!fs.existsSync(proofPath)) {
    console.error(`  ERROR: Proof not found: ${proofPath}`);
    console.error('  Run npm run test:generate first');
    process.exit(1);
  }

  if (!fs.existsSync(vkeyPath)) {
    console.error(`  ERROR: Verification key not found: ${vkeyPath}`);
    console.error('  Run ./scripts/trusted-setup.sh first');
    process.exit(1);
  }

  const proof = JSON.parse(fs.readFileSync(proofPath, 'utf8'));
  const publicSignals = JSON.parse(fs.readFileSync(publicPath, 'utf8'));
  const vkey = JSON.parse(fs.readFileSync(vkeyPath, 'utf8'));

  console.log('  Proof loaded');
  console.log('  Public signals loaded');
  console.log('  Verification key loaded');
  console.log('');

  // ============================================
  // STEP 2: Display public signals
  // ============================================
  console.log('Step 2: Public signals (visible on-chain):');
  console.log('');

  // Public signals order:
  // [0] commitment (output)
  // [1] nullifierHash (output)
  // [2] currentTimestamp (input)
  // [3] maxAttestationAge (input)
  // [4] serverPubCommitment (input)

  console.log('  Outputs:');
  console.log(`    commitment:        ${publicSignals[0].slice(0, 40)}...`);
  console.log(`    nullifierHash:     ${publicSignals[1].slice(0, 40)}...`);
  console.log('');
  console.log('  Public inputs:');
  if (publicSignals.length > 2) {
    console.log(`    currentTimestamp:    ${publicSignals[2]}`);
    console.log(`    maxAttestationAge:   ${publicSignals[3]}`);
    console.log(`    serverPubCommitment: ${publicSignals[4].slice(0, 40)}...`);
  }
  console.log('');

  // ============================================
  // STEP 3: Verify the proof
  // ============================================
  console.log('Step 3: Verifying proof...');
  console.log('');

  const startTime = Date.now();

  const isValid = await snarkjs.groth16.verify(vkey, publicSignals, proof);

  const verifyTime = Date.now() - startTime;

  console.log(`  Verification time: ${verifyTime}ms`);
  console.log('');

  if (isValid) {
    console.log('  =========================================');
    console.log('  |                                       |');
    console.log('  |   ✓ PROOF VERIFIED SUCCESSFULLY!      |');
    console.log('  |                                       |');
    console.log('  =========================================');
  } else {
    console.log('  =========================================');
    console.log('  |                                       |');
    console.log('  |   ✗ PROOF VERIFICATION FAILED!        |');
    console.log('  |                                       |');
    console.log('  =========================================');
  }
  console.log('');

  // ============================================
  // STEP 4: Show what this means
  // ============================================
  console.log('Step 4: What this proves:');
  console.log('');
  console.log('  The prover has demonstrated (in zero-knowledge) that:');
  console.log('');
  console.log('  1. They know an identityHash that was attested by the server');
  console.log('     (without revealing the identityHash)');
  console.log('');
  console.log('  2. The server attestation is recent (within maxAttestationAge)');
  console.log('     (without revealing the exact attestation timestamp)');
  console.log('');
  console.log('  3. The commitment uniquely binds to their identityHash');
  console.log('     (can be stored in merkle tree for future proofs)');
  console.log('');
  console.log('  4. The nullifierHash prevents replay attacks');
  console.log('     (same identityHash + nullifierSecret = same nullifierHash)');
  console.log('');

  // ============================================
  // STEP 5: Export for Soroban
  // ============================================
  console.log('Step 5: Soroban integration data:');
  console.log('');

  // Format proof for Soroban's groth16-verifier contract
  const sorobanProof = {
    a: {
      x: proof.pi_a[0],
      y: proof.pi_a[1]
    },
    b: {
      x: [proof.pi_b[0][0], proof.pi_b[0][1]],
      y: [proof.pi_b[1][0], proof.pi_b[1][1]]
    },
    c: {
      x: proof.pi_c[0],
      y: proof.pi_c[1]
    }
  };

  const sorobanData = {
    proof: sorobanProof,
    publicInputs: publicSignals,
    commitment: publicSignals[0],
    nullifierHash: publicSignals[1]
  };

  const sorobanPath = path.join(__dirname, '..', 'build', 'soroban_proof.json');
  fs.writeFileSync(sorobanPath, JSON.stringify(sorobanData, null, 2));

  console.log(`  Soroban proof data saved to: ${sorobanPath}`);
  console.log('');
  console.log('  This proof can be submitted to:');
  console.log('    groth16-verifier: CCTML7FQ2QAW4LG2NU33ZEH3CGMY6NV2DK7QQSROMDPZHU43WLNZGUNP');
  console.log('    identity-auth:    (deploy when ready)');
  console.log('');

  // ============================================
  // STEP 6: Tamper test (optional)
  // ============================================
  console.log('Step 6: Tamper detection test...');
  console.log('');

  // Modify one public signal and verify it fails
  const tamperedSignals = [...publicSignals];
  tamperedSignals[0] = (BigInt(tamperedSignals[0]) + BigInt(1)).toString();

  const tamperedValid = await snarkjs.groth16.verify(vkey, tamperedSignals, proof);

  if (!tamperedValid) {
    console.log('  ✓ Tampered proof correctly rejected');
  } else {
    console.log('  ✗ WARNING: Tampered proof was accepted!');
  }
  console.log('');

  console.log('==========================================');
  console.log(' Verification complete!');
  console.log('==========================================');
  console.log('');

  process.exit(isValid ? 0 : 1);
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
